socialmedia/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('web/',include('web.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path("register/",SignUpView.as_view(),name="signup"),
    path("login/",SignInView.as_view(),name="signin"),
    path('index/',IndexView.as_view(),name="index" ),
    path("posts/<int:id>/comment/add",add_comment,name="add-comment"),
    path("post/<int:id>/like/add",like_post_view,name="add-like"),
    path('logout',signout_view,name="sign-out"),
    path("profile/", Profile.as_view(), name='profile'),
    path("user/<int:id>/follower/add", add_follower, name="add-follower"),
    path("user/<int:id>/note/add", add_notes, name="add-note"),
    path("people/", ListPeopleView.as_view(), name="people"),
    path("comment/<int:id>/remove",comment_delete,name="comment-delete"),
    path("add/profile",AddProfile.as_view(),name="addprofile"),
    path("post/<int:id>/remove",post_delete,name="post-delete"),
    
    


]

api/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Count

# Create your models here.

class UserProfile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,related_name="profile")
    proimage=models.ImageField(upload_to="images")
    dob=models.DateField()


class Posts(models.Model):
    title=models.CharField(max_length=250)
    image=models.ImageField(upload_to="images",null=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    created_date=models.DateField(auto_now_add=True)
    like=models.ManyToManyField(User,related_name="likes")

    @property
    def posts_comments(self):
        return self.comments_set.all()

    @property
    def likes(self):
        qs=self.like.all().count()
        return qs

    def _str_(self):
        return self.title

class Comments(models.Model):
    comment=models.CharField(max_length=250)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    post=models.ForeignKey(Posts,on_delete=models.CASCADE)
    created_date=models.DateField(auto_now_add=True)

    def _str_(self):
        return self.comment

class Friends(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower')
    date = models.DateTimeField(auto_now_add=True)

class Notes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    note = models.CharField(max_length=100)
    data = models.DateTimeField(auto_now_add=True)

web/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body style="width: 100%; overflow-x: hidden; background-color: #e3f2fd">

    <!--navbar-->
    <nav class="navbar navbar-expand-lg " style="background-color:  #b8cfe0;>
      <div class="container-fluid">
        <a class="navbar-brand" href="#"></p></a><p class="text-center h4 fw-bold mb-2 mx-1 mx-md-1 mt-1"><i class="fa-brands fa-phoenix-framework">Voyage</i>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{%url 'index'%}"><button type="submit" class="btn fw-bold  ">Home</button></a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{%url 'profile'%}"><button type="submit" class="btn fw-bold  ">User Profile</button></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{%url 'people'%}"><button type="submit" class="btn fw-bold">Follow</button></a>
            </li>  
            
          </ul>          
        </div>
        <a class="navbar-brand" href="{%url 'sign-out'%}"><p class="text-center h4 fw-bold mb-2 mx-1 mx-md-1 mt-1"> <button class="btn btn-info color-dark me-2" type="button">Logout</button></p></a>                  
      </div>
    </nav>
    <!-- end of navbar -->
    {%block body_block%}

    {%endblock%}
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</html>

web/templates/index.html
{%extends 'base.html'%}
{%block body_block%}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
        integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />


</head>

<body>
    <div class="row">
        <div class="col-3">
            <div class="card mt-5 ms-5 border-0 shadow " style="width: 80%; ">
                <img src="{{request.user.profile.proimage.url}}"
                    width="70%" class="card-img-top p-2 rounded" alt="...">
                <div class="card-body text-center">
                    <p class="card-text" style="margin: 0;"><strong>@{{request.user}}</strong></p>
                    <span><small class="">{{request.user.first_name}} </small></span>
                    <span><small class="">{{request.user.last_name}} </small></span>
                    <br>
                    <a href="{% url 'profile' %}" class="btn btn-outline-info btn-sm mt-2"><small>View
                            Profile</small></a>
                </div>
            </div>
        </div>
        <div class="col-5">
            <h4 class="m-3">Activity Feed</h2>

                <div class="card border-0 shadow-sm">
                    <div class="card-body">
                        <div class="input-group" style="width: 100%; height: 3em;">

                            <span class="input-group-text border-0 " data-bs-toggle="modal"
                                data-bs-target="#exampleModal" id="basic-addon1">@</span>
                            <input type="text" class="form-control border-0"
                                placeholder="Share whats on your mind, {{request.user}}. ." aria-label="Username"
                                aria-describedby="basic-addon1" data-bs-toggle="modal" data-bs-target="#exampleModal">
                              

                            
                        </div>

                    </div>
                </div>


                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <form action="" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {{form.as_p}}
                                    <input class="btn btn-outline-info form-control btn-sm" type="submit" name="" id=""
                                        value="Add">
                                </form>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>




                <!-- <div class="card mt-3">
                <div class="card-body">
                    <form action="" method="post" enctype="multipart/form-data">
                        {%csrf_token%}
                        {{form.as_p}}
                        <input type="submit" class="btn btn-outline-dark form-control" value="submit">
                    </form>
                </div>
            </div> -->

                {%for p in posts%}
                
                <div class="card mt-3 border-0 shadow">
                    <div class="card-body">
                        <a href="{%url 'post-delete' p.id%}"><i class="fa-sharp fa-solid fa-trash" style="color: black;"></i></a>
                        
                        <p class="text-right fw-bold" style="display: inline;">@{{p.user}}</p>
                        <small>{{p.created_date}}</small>
                        

                        

                        <img src="{{p.image.url}}" class="mt-2" alt="" width="100%" height="400">
                        <p>{{p.title}}</p>
                        
                        <a href="{% url 'add-like' p.id %}" class="btn btn-outline-dark"><i
                                class="fa-solid fa-heart"></i>{{p.likes}}</a>

                                
                                
                                
                        <!-- <button class="btn btn-outline-dark"><i class="fa-regular fa-comments"></i></button>
                        <hr>
                        <form action="{%url 'add-comment' p.id%}" method="post">
                            {%csrf_token%}
                            <input type="text" class="form-control" name="comment" required placeholder="Add comment">
                            <button type="submit" class="btn btn-outline-dark btn-sm mt-1">Comments</button>
                        </form> -->

                        <button type="button" class="btn btn-outline-dark  collapsed"
                        data-bs-toggle="collapse" data-bs-target="#flush-collapse{{p.id}}" aria-expanded="false"
                        aria-controls="flush-collapseOne"><i class="fa-regular fa-comments"></i></button>
                    <hr>
                    <form action="{%url 'add-comment' p.id%}" method="post">
                        {%csrf_token%}
                        <input type="text" class="form-control" name="comment" required placeholder="Add comment">
                        <button type="submit" class="btn btn-outline-dark btn-sm mt-1">Comments</button>
                        
                        
                    </form>

                   


                        <div>
                            {%for comment in p.posts_comments%}
                            <div class="card-body bg-light mt-2">
                                <p style="display: inline;"><small>@{{comment.user}}</small></p>
                                <small>{{comment.created_date}}</small>
                                <p>{{comment.comment}}</p>
                                <a href="{%url 'comment-delete' comment.id%}"><i class="fa-sharp fa-solid fa-trash" style="color: black;"></i></a>
                            </div>
                            {%endfor%}
                        </div>
                    </div>
                </div>
                {%endfor%}
        </div>
        <div class="col-4">
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
                integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
                crossorigin="anonymous" />

            <style>
                .parent {
                    display: grid;
                    grid-gap: 5px;
                    grid-column-gap: 0px;
                    grid-template-columns: 1fr 1fr 1fr 1fr;
                    grid-row-gap: 5px;
                    grid-column-gap: 5px;
                    padding: 1em;
                }
            </style>
            

            <div class="following">
                <h5 class="m-3">Following</h5>
                <div class="card parent border-0 shadow-sm" style="width: 90%;">
                    {% for f in followings %}
                    <div class="card child border-0 shadow-sm" style="width: 100%;">
                        <div class="card-body text-center">
                            <img src="/images/con.jpg"
                                class="rounded-circle" width="100%" alt="">
                            <small style="font-size: 0.8em;">{{f.user}}</small>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <!-- <h5 class="mt-5"> Take your Notes here</h5> -->

                <!-- <div class="card p-3 mt-3 border-0 shadow-sm" style="width: 90%;">
                    <div class="card-body">
                        <div class="row main "> -->

                            <!-- <div class="card mb-3 border-0 child" style="max-width: 100%;">
                                <div class="row g-0"> -->


                                    <div class="container my-3">
                                        <div class="card">
                                            <div class="card-body">
                                                <h5 class="card-title">
                                                    Leave a Note

                                                <form action="{% url 'add-note' request.user.id %}" method="post">
                                                    
                                                    {% csrf_token %}
                                                    <div class="form-group mb-2">
                                                        <textarea class="form-control" id="id_note" name="note" rows="1"></textarea>
                                                    </div>
                                                    <button  class="btn btn-outline-info btn-sm form-control">Add Note</a>
                                                        
                                                </form>
                                                
                                                
                                            <!-- </div> -->
                                        <!-- </div> -->
                                         
                                    </div>
                                    


                                </div>

                                <div class="mt-2 card p-4">
                                    {% for i in notes %}
                                    <div class="card mt-2">
                                        <div class="card-body">
                                            <p><small>@{{i.user}}</small></p>
                                            <p>{{i.note}}</p>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            <!-- </div> -->
                        </div>

                    </div>
                <!-- </div> -->

              
            </div>

        </div>
    </div>
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
    crossorigin="anonymous"></script>

</html>





<!-- 
<form action="" method="post" enctype="multipart/form-data">
    {%csrf_token%}
    {{form.as_p}}
    <input type="submit" value="submit">
</form>


{%for p in posts%}
{{p.user}}
{{p.title}}
<img src="{{p.image.url}}" alt="">
{{p.created_date}}

{{p.likes}}
<a href="{%url 'add-like' p.id %}" class="btn btn-outline-secondary">Like</a>

<form action="{%url 'add-comment' p.id%}" method="post">
    {%csrf_token%}
    <input type="text" class="form-control" name="comment" required>
    <button type="submit" class="btn btn-dark"> Add Comment</button>
</form>

{%for comment in p.posts_comments%}
{{comment.user}}
{{comment.comment}}
{{comment.created_date}}
{%endfor%}
{%endfor%}
{%endblock%} -->

web/templates/list_people.html
{% extends 'base.html' %}

{% block body_block %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/web/static/css/loginstyle.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
    integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    

    <title>Document</title>
</head>
<body>
<div class="row">
    <div class="col-3"></div>
    <div class="col-5">
        <h2>People</h2>
        {% for person in people %}
        <div class="card mb-3" style="max-width: 540px;">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="/images/con.jpg"
                    {% comment %} https://moonvillageassociation.org/wp-content/uploads/2018/06/default-profile-picture1.jpg {% endcomment %}
                        class="img-fluid rounded-start p-3" alt="...">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{{person.username}}</h5>

                        <a href="{% url 'add-follower' person.id %}" class="btn btn-ouline-success"><i class="fa-brands fa-phoenix-framework"></i>follow</a>

                        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="col-4">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
            crossorigin="anonymous" />

        <style>
            .parent {
                display: grid;
                grid-gap: 5px;
                grid-column-gap: 0px;
                grid-template-columns: 1fr 1fr 1fr 1fr;
                grid-row-gap: 5px;
                grid-column-gap: 5px;
                padding: 1em;
            }
        </style>


        <div class="following">
            <h5>Following</h5>
            <div class="card parent border-0 shadow-sm" style="width: 90%;">
                {% for f in followings %}
                <div class="card child border-0 shadow-sm" style="width: 100%;">
                    <div class="card-body text-center">
                        <img src="/images/con.jpg"
                            class="rounded-circle" width="100%" alt="">
                        <small style="font-size: 0.8em;">{{f.user}}</small>
                    </div>
                </div>
                {% endfor %}
            </div>

        </div>
    </div>
</div>
</body>

{% endblock %}

web/templates/login.html
<!-- 
    <form action="" method="post">
        {%csrf_token%}
        {{form.as_p}}
        <input type="submit" value="submit">
    </form>
     -->


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/web/static/css/loginstyle.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
    integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    

    <title>Document</title>
</head>

<body>

    <body>
        <section class="vh-100 bg-image"
        style="background-color:  #b8cfe0;">
        <div class="container">
            <div class="row">
                <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                    <div class="card border-0 shadow rounded-3 my-5">
                        <div class="card-body p-4 p-sm-5">
                            <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4"> <i class="fa-brands fa-phoenix-framework"></i>Sign in to voyage</p>
                        
                            <form method="post" enctype="multipart/form-data">
                                {%csrf_token%}
                                <div class="form-floating mb-3">
                                    <input type="text" class="form-control" id="floatingInput"
                                        placeholder="name@example.com" name="username">
                                    <label for="floatingInput">User Name</label>
                                </div>
                                <div class="form-floating mb-3">
                                    <input type="password" class="form-control" id="floatingPassword"
                                        placeholder="Password" name="password">
                                    <label for="floatingPassword">Password</label>
                                </div>

                                <div class="form-check mb-3">
                                    <input class="form-check-input" type="checkbox" value="" id="rememberPasswordCheck">
                                    <label class="form-check-label" for="rememberPasswordCheck">
                                        Remember password
                                    </label>
                                </div>
                                <div class="d-grid">
                                    <button class="btn btn-info btn-login text-uppercase fw-bold" type="submit">Sign
                                        in</button>
                                </div>
                               
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
</html>

web/templates/notes.html
<h5 class="mt-5">Trending Posts</h5>

            <div class="card p-3 mt-3 border-0 shadow-sm" style="width: 90%;" >
                <div class="card-body">
                    <div class="row main ">
                        {% for t in posts %}
                        <div class="card mb-3 border-0 child" style="max-width: 100%;">
                            <div class="row g-0">
                              
                                    
                                    <div class="container my-3">
                                        <h1>Take your Notes here</h1>
                                        <div class="card">
                                            <div class="card-body">
                                                <h5 class="card-title">
                                                    Add a Note
                                                  
                                                </h5>
                                                <div class="form-group">
                                                    <textarea class="form-control" 
                                                        id="addTxt" rows="3">
                                                    </textarea>
                                                </div>
                                                <button class="btn btn-primary" 
                                                    id="addBtn" style=
                                                    "background-color:green">
                                                    Add Note
                                                </button>
                                            </div>
                                        </div>
                                        <hr>
                                        <h1>Your Notes</h1>
                                        <hr>
                                          
                                        <div id="notes" class=
                                            "row container-fluid"> 
                                        </div>
                                    </div>


                              
                              </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>  
                </div>
            </div>

web/templates/profile.html
{% extends 'base.html' %}


{% block body_block %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
    integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
   
    
    <div class="row">
    
        <div class="col-4">
            <div class="p-5">
                <div class="card" style="width: 95%; margin-top: -2em;">
                    <img src="{{request.user.profile.proimage.url}}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <p class="card-text" style="margin: 0;"><strong>@{{request.user}}</strong></p>
            <small class="text-center h4 fw-bold mb-2 mx-1 mx-md-1 mt-1"><i class="fa-brands fa-phoenix-framework">Voyage</i>
                    <a href="{%url 'addprofile'%}" class="btn btn-info btn-sm form-control">add profile</a>       
                    </div>
                  </div>
            </div>
        </div>
        <div class="col-5">
            
    
            {%for p in posts%}
                <div class="card mt-3">
                    <div class="card-body">
                        <p class="text-right h5 fw-bold mb-5 mx-1 mx-md-4 mt-4">@{{p.user}}</p>
                        <small>{{p.created_date}}</small>
                        <img src="{{p.image.url}}" alt="" width="100%" height="700">
                        <p>{{p.title}}</p>
                        <a href="{% url 'add-like' p.id %}" class="btn btn-outline-dark"><i class="fa-solid fa-heart"></i>{{p.likes}}</a>
                        <button class="btn btn-outline-dark"><i class="fa-regular fa-comments"></i></button>
                        <hr>
                        <form action="{%url 'add-comment' p.id%}" method="post">
                            {%csrf_token%}
                            <input type="text" class="form-control" name="comment" required placeholder="Add comment">
                            <button type="submit" class="btn btn-outline-dark btn-sm mt-1">Comments</button>
                        </form>
                        <div>
                            {%for comment in p.posts_comments%}
                            <div class="card-body bg-light mt-2">
                                <p style="display: inline;"><small>@{{comment.user}}</small></p>
                                <small>{{comment.created_date}}</small>
                                <p>{{comment.comment}}</p>
                            </div>
                            {%endfor%}
                        </div>
                    </div>
                </div>
                {%endfor%}
        </div>
        <div class="col-4"></div>
    </div>
    
    
    
    
    
    
    {%endblock%}
</body>
</html>

web/templates/user_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
    integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <title>Document</title>
</head>
<body>

    <section class="vh-100 bg-image"
    style="background-color:  #b8cfe0;">
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <div class="card border-0 shadow rounded-3 my-5">
                    <div class="card-body p-4 p-sm-5">
                        <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4"> <i class="fa-brands fa-phoenix-framework"></i>Add Profile</p>
    {% comment %} <div class="container">
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4"> {% endcomment %}
                <form action="" method="post" enctype="multipart/form-data">
                    {%csrf_token%}
                    
                    {{form.as_p}}
                    
                    <button class="btn btn-info btn-login text-uppercase fw-bold" type="submit">add</button>                                   
                    
                </form>
            </div>
            <div class="col-4"></div>
        </div>
    </div>
    
</body>
</html>